Add configurable TIMEZONE and SSH access limit for EC2

diff --git a/modules/sub-modules/templates/vault_config/init_license.yml.tmpl b/modules/sub-modules/templates/vault_config/init_license.yml.tmpl
--- a/modules/sub-modules/templates/vault_config/init_license.yml.tmpl
+++ b/modules/sub-modules/templates/vault_config/init_license.yml.tmpl
@@ -8,9 +8,7 @@ touch /home/ubuntu/_vaultSetup/vault_debug
 sudo chown -R vault:vault /home/ubuntu/_vaultSetup
 sudo chown ubuntu:ubuntu /home/ubuntu
 
-echo "$(date): Initializing Vault..."|sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
-
-echo "Initializing Vault..."
+echo "`date`: Initializing Vault..."|sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
 # Wait for Vault to start 
 sleep 1
 
@@ -30,16 +28,15 @@ EOF
 
 
 # Install the Vault license and deletes the license file
-function install_vault_license () {
-  
+function install_vault_license() {
+
 curl -s --request PUT --header "X-Vault-Token: $1" --data @/home/ubuntu/_vaultSetup/license.json https://127.0.0.1:8200/v1/sys/license
 
 if [ $? -eq 0 ]
 then
-    #rm /home/ubuntu/_vaultSetup/license.json
-    echo "$(date): Writing license file result: OK"|sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
+   echo "`date`: Writing license file result: OK"|sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
 else
-    echo "$(date): Writing license file result: FAILED"|sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
+   echo "`date`: Writing license file result: FAILED"|sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
 fi
 }
 
@@ -47,8 +44,8 @@ fi
 sleep 10
 
 # Check if Vault is ready for being licensed
-while true
-do
+while true 
+do 
   if [[ $(curl -X GET -LI -o /dev/null -w '%%{http_code}' -s https://127.0.0.1:8200/v1/sys/health) =~ (200|429|473) ]] # HTTP codes that show if Vault is ready to be used
   then
     # Checking if Vault is using autoloading license (version > 1.8) if 404 is returned, autoload is not used, so installing the license via /sys/license endpoint
@@ -59,27 +56,23 @@ do
     # If autoloading license is used, break from the loop
     elif [[ $(curl -X GET -LI -H "X-Vault-Token: $ROOT_TOKEN" -o /dev/null -w '%%{http_code}' -s https://127.0.0.1:8200/v1/sys/license/status) =~ (200) ]]
     then
-    {
-      echo "$(date): AUTOLOADING is used!"|sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
+      echo "`date`: AUTOLOADING is used!"|sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
       break 2
-      }
     fi
-  echo "$(date): Vault is not ready yet!" |sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
+  echo "`date`: Vault is not ready yet!" |sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
   sleep 1
   fi
 done
 
-## Add audit file
-#curl -s -X PUT --header "X-Vault-Token: $ROOT_TOKEN" -H "X-Vault-Request: true" -d '{"type":"file","description":"Audit file","options":{"file_path":"/opt/vault/audit.log"},"local":false}' https://127.0.0.1:8200/v1/sys/audit/file
-#
-#if [ $? -eq 0 ].
-#then
-#   echo "$(date): Audit enabled: OK"|sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
-#   retval="OK"
-#else
-#   echo "$(date): Audit enabled: FAILED"|sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
-#fi
-##
+curl -s -X PUT --header "X-Vault-Token: $ROOT_TOKEN" -H "X-Vault-Request: true" -d '{"type":"file","description":"Audit file","options":{"file_path":"/opt/vault/audit.log"},"local":false}' https://127.0.0.1:8200/v1/sys/audit/file
+
+if [ $? -eq 0 ] 
+then
+   echo "`date`: Audit enabled: OK"|sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
+   retval="OK"
+else
+   echo "`date`: Audit enabled: FAILED"|sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
+fi
 
 # For debugging
-echo "$(date): This is an active node, other nodes join to it" |sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
+echo "$(date): This is an active node. Other nodes will join to this node." |sudo tee -a /home/ubuntu/_vaultSetup/vault_debug
